create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports -filter { NAME =~  "*clk*" && DIRECTION == "IN" }]


set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property PACKAGE_PIN G19 [get_ports {vga_data[11]}]
set_property PACKAGE_PIN H19 [get_ports {vga_data[10]}]
set_property PACKAGE_PIN J19 [get_ports {vga_data[9]}]
set_property PACKAGE_PIN N19 [get_ports {vga_data[8]}]
set_property PACKAGE_PIN J17 [get_ports {vga_data[7]}]
set_property PACKAGE_PIN H17 [get_ports {vga_data[6]}]
set_property PACKAGE_PIN G17 [get_ports {vga_data[5]}]
set_property PACKAGE_PIN D17 [get_ports {vga_data[4]}]
set_property PACKAGE_PIN N18 [get_ports {vga_data[3]}]
set_property PACKAGE_PIN L18 [get_ports {vga_data[2]}]
set_property PACKAGE_PIN K18 [get_ports {vga_data[1]}]
set_property PACKAGE_PIN J18 [get_ports {vga_data[0]}]
set_property PACKAGE_PIN P19 [get_ports vga_href]
set_property PACKAGE_PIN R19 [get_ports vga_vsync]
set_property PACKAGE_PIN U16 [get_ports vga_de]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_de]
set_property IOSTANDARD LVCMOS33 [get_ports vga_href]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

set_property PACKAGE_PIN W19 [get_ports {key_in[1]}]
set_property PACKAGE_PIN T17 [get_ports {key_in[2]}]
set_property PACKAGE_PIN T18 [get_ports {key_in[3]}]
set_property PACKAGE_PIN U17 [get_ports {key_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[0]}]
